name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # 👈 Espera que el job "test" pase
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-k8s-demo:latest
  deploy:
            runs-on: self-hosted
            needs: build-and-push
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
        
              - name: Aplicar manifiestos en Minikube
                run: |
                  kubectl apply -f k8s/namespace.yaml
                  kubectl apply -f k8s/rbac.yaml
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/service.yaml
              - name: Force rollout restart
                run: kubectl rollout restart deployment/api-demo -n api-demo
        